const CATEGORY_ICONS: Record<string, string> = {
  "cat-desserts": "/category-icons/deserty.svg",
  "cat-semi": "/category-icons/polufabrikaty.svg",
  "cat-meat": "/category-icons/myaso.svg",
  "cat-lunch": "/category-icons/gotovye-obedy.svg",
  "cat-banquet": "/category-icons/deserty.svg",
  deserty: "/category-icons/deserty.svg",
  polufabrikaty: "/category-icons/polufabrikaty.svg",
  myaso: "/category-icons/myaso.svg",
  "gotovye-obedy": "/category-icons/gotovye-obedy.svg",
  "banketnye-deserty": "/category-icons/deserty.svg",
};

/** Returns true when `src` is an auto-generated SVG placeholder from /products/ */
export function isAutoGeneratedPlaceholder(src: string | undefined): boolean {
  if (!src) return true;
  return src.startsWith("/products/") && src.endsWith(".svg");
}

/** Returns the category icon path for a given category id or slug, or null if unknown */
export function getCategoryIcon(categoryIdOrSlug: string | undefined): string | null {
  if (!categoryIdOrSlug) return null;
  return CATEGORY_ICONS[categoryIdOrSlug] ?? null;
}
