/* ============================================================================
   DC BAKERY — ПРОТОТИП РЕДИЗАЙНА · data.js
   ---------------------------------------------------------------------------
   Статические демонстрационные данные. Backend не подключён.

   Источник данных: рабочий сайт DC Bakery (src/data/products.ts,
   src/data/promotions.ts, src/lib/site-content.ts, app/constants.ts,
   app/(main)/contacts/page.tsx). Названия, цены, состав, фасовка, сроки,
   контакты и условия акции — реальные.

   ЧТО ИЗМЕНЕНО СПЕЦИАЛЬНО ДЛЯ ПРОТОТИПА (помечено DEMO):
   · stock — в реальном каталоге у всех позиций 10. Здесь значения разведены,
     чтобы были видны состояния «в наличии» / «мало» / «нет в наличии».
   · orders, profile — демонстрационные, показывают дизайн кабинета.
   · promo.progress — три состояния шкалы награды (0% / 65% / получено).
   ========================================================================== */

/* --------------------------------------------------------------------------
   1. КОНСТАНТЫ И НАСТРОЙКИ
   -------------------------------------------------------------------------- */

const CONFIG = {
  minOrderAmount: 15000,          // реальный минимум B2B-заказа, ₸
  currency: "₸",
  lowStockThreshold: 5,           // «мало» — когда остаток ≤ 5
  deliveryDays: [2, 4, 6],        // вт · чт · сб
  orderCutoffHour: 18,            // приём заявок до 18:00 накануне
  freeDeliveryFrom: 15000,
  paidDeliveryRange: "1 500–3 000 ₸",
  // TODO(backend): реальный URL розничного сайта del Cappuccino.
  // В коде рабочего сайта значение приходит из NEXT_PUBLIC_RETAIL_SITE_URL,
   // фолбэк — https://example.com, то есть реальный адрес в проекте не задан.
  retailUrl: "#",
};

/* --------------------------------------------------------------------------
   2. КОНТАКТЫ И РЕКВИЗИТЫ (реальные данные сайта)
   -------------------------------------------------------------------------- */

const CONTACTS = {
  whatsapp: "+7 747 727 2650",
  whatsappHref: "https://wa.me/77477272650",
  phone: "+7 747 694 0766",
  phoneHref: "tel:+77476940766",
  email: "info@dc-bakery.kz",
  instagram: "@bakery.dc",
  instagramHref: "https://www.instagram.com/bakery.dc",
  address: "г. Алматы, ул. Жамбыла 154",
  workHours: "Пн–Пт 9:00–19:00",
  site: "dc-bakery.kz",
  deliveryDaysLabel: "Вторник · Четверг · Суббота",
  cutoffLabel: "Приём заявок до 18:00 накануне",
};

const REQUISITES = {
  legalName: "ИП Кошкаров Асылбек Касымбекович",
  legalNameUpper: "ИП КОШКАРОВ АСЫЛБЕК КАСЫМБЕКОВИЧ",
  bin: "810127300096",
  registration: "Талон о госрегистрации ИП №KZ26TWQ02214961 от 26.01.2025",
  accounts: [
    {
      title: "Счёт «Пекарня»",
      note: "десерты, выпечка, кондитерские изделия",
      bank: "АО «Kaspi Bank»",
      bic: "CASPKZKA",
      kbe: "19",
      iban: "KZ61722S000051248791",
    },
    {
      title: "Счёт «Цех полуфабрикатов»",
      note: "полуфабрикаты",
      bank: "АО «Kaspi Bank»",
      bic: "CASPKZKA",
      kbe: "19",
      iban: "KZ73722S000051742402",
    },
  ],
};

/* --------------------------------------------------------------------------
   3. КАТЕГОРИИ
   -------------------------------------------------------------------------- */

const CATEGORIES = [
  {
    id: "deserty",
    name: "Десерты",
    slug: "deserty",
    tagline: "Пирожные, торты, рулеты, чизкейки",
    icon: "assets/icons/deserty.svg",
    cover: "assets/products/tort-medovik.webp",
    count: 34,
    subcategories: ["Пирожные", "Чизкейки", "Выпечка", "Рулеты", "Тарталетки", "Торты", "Банкейки", "Шу", "Дениши"],
  },
  {
    id: "polufabrikaty",
    name: "Полуфабрикаты",
    slug: "polufabrikaty",
    tagline: "Пельмени, манты, самса, котлеты",
    icon: "assets/icons/polufabrikaty.svg",
    cover: "assets/products/pelmeni-s-govyadinoy.webp",
    count: 11,
    subcategories: ["Пельмени", "Вареники", "Котлеты", "Сырники", "Манты", "Самса", "Мини-чебуреки"],
  },
  {
    id: "myaso",
    name: "Мясо",
    slug: "myaso",
    tagline: "Мякоть, фарш, стейки",
    icon: "assets/icons/myaso.svg",
    cover: null,
    count: 4,
    subcategories: ["Говядина", "Фарш", "Стейки"],
  },
  {
    id: "banketnye-deserty",
    name: "Банкетные десерты",
    slug: "banketnye-deserty",
    tagline: "Порционные наборы для банкета",
    icon: "assets/icons/deserty.svg",
    cover: "assets/products/tort-medovik-banketnyy.webp",
    count: 4,
    subcategories: ["Банкетный ассортимент"],
  },
];

/* Подборки витрины — кураторские наборы поверх категорий. */
const COLLECTIONS = [
  { id: "popular",  name: "Популярное",        tagline: "Часто берут партнёры" },
  { id: "new",      name: "Новинки",           tagline: "Свежие позиции сезона" },
  { id: "seasonal", name: "Сезонная подборка", tagline: "Лёгкие ягодные и фруктовые вкусы" },
  { id: "showcase", name: "Для витрины",       tagline: "Штучные позиции под кофе" },
];

const COLLECTION_ITEMS = {
  popular:  ["pelmeni-s-govyadinoy", "vareniki-s-kartofelem", "kotlety-govyazhi", "syrniki-klassicheskie", "napoleon", "medovik", "molochnaya-devochka", "snikers", "ispanskiy-chizkeyk", "sinnabon", "fistashkovyy-rulet", "tort-snikers", "banka-keyk-oreo"],
  new:      ["samsa-s-govyadinoy-i-tykvoy", "kukis", "desert-vupi-pay", "tort-vupi-pay", "desert-dubayskiy", "tort-dubayskiy", "desert-fistashka-malina", "tort-fistashka-malina"],
  seasonal: ["desert-fistashka-malina", "shu-yagodnyy", "shu-abrikosovyy", "merengovyy-rulet", "ispanskiy-chizkeyk", "desert-dubayskiy"],
  showcase: ["kukis", "maffin-shokoladnyy", "sinnabon", "denish-s-klubnikoy", "denish-s-persikom", "kartoshka", "tartaletka-bannofi-pay", "banka-keyk-tiramisu"],
};

/* --------------------------------------------------------------------------
   4. ТОВАРЫ — реальный каталог DC Bakery (53 позиции)
   image: null → у позиции нет фотографии, карточка показывает
   спроектированную нейтральную заглушку с названием товара.
   -------------------------------------------------------------------------- */

const PRODUCTS = [
  {
    id: "pelmeni-s-govyadinoy",
    slug: "pelmeni-s-govyadinoy",
    name: "Пельмени с говядиной",
    category: "Полуфабрикаты",
    subcategory: "Пельмени",
    description: "Классические пельмени с сочной говяжьей начинкой и тонким тестом.",
    composition: "Говядина мякоть, лук репчатый, говяжий жир, соль, черный перец, мука высший сорт, яйцо куриное.",
    compositionKz: "Сиыр еті, пияз, бидай ұны, су",
    weightLabel: "500 грамм",
    weightGrams: 500,
    unit: "г",
    price: 2124,
    stock: 30, // DEMO
    storage: "Хранить при -18°C",
    shelfLife: "6 мес.",
    packageType: "вакуум",
    isHalal: true,
    isPopular: true,
    isNew: false,
    image: "assets/products/pelmeni-s-govyadinoy.webp",
  },
  {
    id: "vareniki-s-kartofelem",
    slug: "vareniki-s-kartofelem",
    name: "Вареники с картофелем",
    category: "Полуфабрикаты",
    subcategory: "Вареники",
    description: "Вареники с нежной картофельной начинкой в тонком тесте.",
    composition: "Мука пшеничная, вода, яйцо куриное, картофель, лук репчатый, соль, перец.",
    compositionKz: "Картоп, пияз, бидай ұны, су, жұмыртқа, өсімдік майы, тұз",
    weightLabel: "500 грамм",
    weightGrams: 500,
    unit: "г",
    price: 850,
    stock: 37, // DEMO
    storage: "Хранить при -18°C",
    shelfLife: "6 мес.",
    packageType: "вакуум",
    isHalal: true,
    isPopular: true,
    isNew: false,
    image: "assets/products/vareniki-s-kartofelem.webp",
  },
  {
    id: "kotlety-govyazhi",
    slug: "kotlety-govyazhi",
    name: "Котлеты говяжьи",
    category: "Полуфабрикаты",
    subcategory: "Котлеты",
    description: "Домашние говяжьи котлеты с сочной мясной текстурой.",
    composition: "Мякоть говядина, говяжий жир, лук репчатый, соль, черный перец, панировочные сухари.",
    compositionKz: "Сиыр еті, пияз, бидай ұны, су",
    weightLabel: "4 шт — 280 грамм",
    weightGrams: 280,
    unit: "г",
    price: 3160,
    stock: 32, // DEMO
    storage: "Хранить при -18°C",
    shelfLife: "6 мес.",
    packageType: "вакуум",
    isHalal: true,
    isPopular: true,
    isNew: false,
    image: "assets/products/kotlety-govyazhi.webp",
  },
  {
    id: "kotlety-kurinye",
    slug: "kotlety-kurinye",
    name: "Котлеты куриные",
    category: "Полуфабрикаты",
    subcategory: "Котлеты",
    description: "Домашние котлеты из нежного куриного филе.",
    composition: "Куриное филе, лук репчатый, соль, черный перец, панировочные сухари, куриный бульон.",
    compositionKz: "Тауық филесі, пияз, ақ нан, жұмыртқа, су, тұз, бұрыш",
    weightLabel: "4 шт — 240 грамм",
    weightGrams: 240,
    unit: "г",
    price: 1846,
    stock: 5, // DEMO
    storage: "Хранить при -18°C",
    shelfLife: "6 мес.",
    packageType: "вакуум",
    isHalal: true,
    isPopular: false,
    isNew: false,
    image: "assets/products/kotlety-kurinye.webp",
  },
  {
    id: "syrniki-s-irimshikom",
    slug: "syrniki-s-irimshikom",
    name: "Сырники с иримшиком",
    category: "Полуфабрикаты",
    subcategory: "Сырники",
    description: "Нежные сырники с добавлением иримшика.",
    composition: "Творог, сахар, иримшик, яйцо куриное, мука 1 сорт, ванильный сахар, манная крупа.",
    compositionKz: "Сүзбе, ірімшік, тауық жұмыртқасы, бидай ұны, қант",
    weightLabel: "6 шт — 360 грамм",
    weightGrams: 360,
    unit: "г",
    price: 1420,
    stock: 30, // DEMO
    storage: "Хранить при -18°C",
    shelfLife: "6 мес.",
    packageType: "вакуум",
    isHalal: true,
    isPopular: false,
    isNew: false,
    image: "assets/products/syrniki-s-irimshikom.webp",
  },
  {
    id: "syrniki-klassicheskie",
    slug: "syrniki-klassicheskie",
    name: "Сырники классические",
    category: "Полуфабрикаты",
    subcategory: "Сырники",
    description: "Золотистые творожники из натурального творога с тонким ароматом ванили.",
    composition: "Творог, яйцо куриное, ванильный сахар, сахар, мука 1 сорт, манная крупа.",
    compositionKz: "Сүзбе, тауық жұмыртқасы, бидай ұны/манна жармасы, қант, тұз, ванилин",
    weightLabel: "6 шт по 60 грамм — 360 грамм",
    weightGrams: 360,
    unit: "г",
    price: 1228,
    stock: 37, // DEMO
    storage: "Хранить при -18°C",
    shelfLife: "6 мес.",
    packageType: "вакуум",
    isHalal: true,
    isPopular: true,
    isNew: false,
    image: "assets/products/syrniki-klassicheskie.webp",
  },
  {
    id: "manty-s-govyadinoy-i-tykvoy",
    slug: "manty-s-govyadinoy-i-tykvoy",
    name: "Манты с говядиной и тыквой",
    category: "Полуфабрикаты",
    subcategory: "Манты",
    description: "Сочные манты с говядиной, тыквой и специями.",
    composition: "Говядина мякоть, говяжий жир, мука высший сорт, яйцо куриное, тыква, соль, черный перец, лук репчатый.",
    compositionKz: "Сиыр еті, пияз, бидай ұны, су, тұз, зире, бұрыш",
    weightLabel: "10 шт по 50 грамм — 0,5 кг",
    weightGrams: 500,
    unit: "г",
    price: 2060,
    stock: 19, // DEMO
    storage: "Хранить при -18°C",
    shelfLife: "6 мес.",
    packageType: "вакуум",
    isHalal: true,
    isPopular: false,
    isNew: false,
    image: "assets/products/manty-s-govyadinoy-i-tykvoy.webp",
  },
  {
    id: "samsa-s-govyadinoy-i-tykvoy",
    slug: "samsa-s-govyadinoy-i-tykvoy",
    name: "Самса с говядиной и тыквой",
    category: "Полуфабрикаты",
    subcategory: "Самса",
    description: "Слоёная самса с сочной начинкой из говядины, тыквы и специй.",
    composition: "Говяжий фарш, лук репчатый, тыква, соль, перец, мука высший сорт, сливочное масло 72,5%, говяжий жир.",
    compositionKz: "Сиыр еті, асқабақ, пияз, бидай ұны, су, сары май, тұз, дәмдеуіштер",
    weightLabel: "8 шт по 65 грамм — 0,5 кг",
    weightGrams: 500,
    unit: "г",
    price: 1932,
    stock: 19, // DEMO
    storage: "Хранить при -18°C",
    shelfLife: "6 мес.",
    packageType: "вакуум",
    isHalal: true,
    isPopular: false,
    isNew: true,
    image: "assets/products/samsa-s-govyadinoy-i-tykvoy.webp",
  },
  {
    id: "samsa-s-kuritsey",
    slug: "samsa-s-kuritsey",
    name: "Самса с курицей",
    category: "Полуфабрикаты",
    subcategory: "Самса",
    description: "Слоёная самса с сочной куриной начинкой.",
    composition: "Мука высший сорт, яйцо куриное, сливочное масло 72,5%, куриное филе, лук репчатый, соль, черный перец.",
    compositionKz: "Тауық филесі, пияз, бидай ұны, су, сары май, тұз, дәмдеуіштер",
    weightLabel: "8 шт по 65 грамм — 0,5 кг",
    weightGrams: 500,
    unit: "г",
    price: 1260,
    stock: 0, // DEMO
    storage: "Хранить при -18°C",
    shelfLife: "6 мес.",
    packageType: "вакуум",
    isHalal: true,
    isPopular: false,
    isNew: false,
    image: "assets/products/samsa-s-kuritsey.webp",
  },
  {
    id: "mini-chebureki-s-dzhusaem",
    slug: "mini-chebureki-s-dzhusaem",
    name: "Мини-чебуреки с джусаем",
    category: "Полуфабрикаты",
    subcategory: "Мини-чебуреки",
    description: "Сочные мини-чебуреки с говяжьим фаршем и ароматным джусаем.",
    composition: "Говядина мякоть, джусай, говяжий жир, соль, перец черный, мука, яйцо куриное.",
    compositionKz: "Сиыр еті, жусай, бидай ұны, су",
    weightLabel: "500 грамм",
    weightGrams: 500,
    unit: "г",
    price: 2700,
    stock: 35, // DEMO
    storage: "Хранить при -18°C",
    shelfLife: "6 мес.",
    packageType: "вакуум",
    isHalal: true,
    isPopular: false,
    isNew: false,
    image: "assets/products/mini-chebureki-s-dzhusaem.webp",
  },
  {
    id: "mini-chebureki-s-govyazhim-farshem-i-lukom",
    slug: "mini-chebureki-s-govyazhim-farshem-i-lukom",
    name: "Мини-чебуреки с говяжьим фаршем и луком",
    category: "Полуфабрикаты",
    subcategory: "Мини-чебуреки",
    description: "Классические мини-чебуреки с говяжьим фаршем и луком.",
    composition: "Говядина мякоть, лук репчатый, говяжий жир, соль, перец черный, мука, яйцо куриное.",
    compositionKz: "Сиыр еті, пияз, бидай ұны, су",
    weightLabel: "500 грамм",
    weightGrams: 500,
    unit: "г",
    price: 2900,
    stock: 34, // DEMO
    storage: "Хранить при -18°C",
    shelfLife: "6 мес.",
    packageType: "вакуум",
    isHalal: true,
    isPopular: false,
    isNew: false,
    image: "assets/products/mini-chebureki-s-govyazhim-farshem-i-lukom.webp",
  },
  {
    id: "myaso-govyadiny",
    slug: "myaso-govyadiny",
    name: "Мякоть говядины",
    category: "Мясо",
    subcategory: "Говядина",
    description: "Постная мякоть говядины для жарки, тушения или запекания.",
    composition: "Говядина.",
    compositionKz: "Сиыр еті",
    weightLabel: "500 грамм",
    weightGrams: 500,
    unit: "г",
    price: 3596,
    stock: 25, // DEMO
    storage: "Хранить при -18°C",
    shelfLife: "12 мес.",
    packageType: "вакуум",
    isHalal: true,
    isPopular: false,
    isNew: false,
    image: null,
  },
  {
    id: "farsh-govyazhiy",
    slug: "farsh-govyazhiy",
    name: "Фарш говяжий",
    category: "Мясо",
    subcategory: "Фарш",
    description: "Говяжий фарш с балансом мяса и жира для котлет, начинок и горячих блюд.",
    composition: "Говядина, жир говяжий.",
    compositionKz: "Сиыр еті, сиыр майы",
    weightLabel: "500 грамм",
    weightGrams: 500,
    unit: "г",
    price: 3596,
    stock: 25, // DEMO
    storage: "Хранить при -18°C",
    shelfLife: "6 мес.",
    packageType: "вакуум",
    isHalal: true,
    isPopular: false,
    isNew: false,
    image: null,
  },
  {
    id: "ribay",
    slug: "ribay",
    name: "Рибай",
    category: "Мясо",
    subcategory: "Стейки",
    description: "Мраморный говяжий стейк рибай с насыщенным мясным вкусом.",
    composition: "Говядина.",
    compositionKz: "Сиыр еті",
    weightLabel: "~250 грамм",
    weightGrams: 250,
    unit: "г",
    price: 3596,
    stock: 15, // DEMO
    storage: "Хранить при -18°C",
    shelfLife: "6 мес.",
    packageType: "вакуум",
    isHalal: true,
    isPopular: false,
    isNew: false,
    image: null,
  },
  {
    id: "tibon",
    slug: "tibon",
    name: "Тибон",
    category: "Мясо",
    subcategory: "Стейки",
    description: "Говяжий T-bone стейк на кости с выразительным вкусом.",
    composition: "Говядина.",
    compositionKz: "Сиыр еті",
    weightLabel: "~250 грамм",
    weightGrams: 250,
    unit: "г",
    price: 3596,
    stock: 15, // DEMO
    storage: "Хранить при -18°C",
    shelfLife: "6 мес.",
    packageType: "вакуум",
    isHalal: true,
    isPopular: false,
    isNew: false,
    image: null,
  },
  {
    id: "napoleon",
    slug: "napoleon",
    name: "Наполеон",
    category: "Десерты",
    subcategory: "Пирожные",
    description: "Классическое сочетание тончайших слоев хрустящего теста и нежного заварного крема.",
    composition: "Мука пшеничная, масло сливочное, молоко, яйцо куриное, уксусная эссенция, сливки кондитерские, сахар свекольный, ванильный сахар.",
    compositionKz: "Қамыр, крем, қаймақ (сливки), крахмал, сірке суы",
    weightLabel: "125 грамм",
    weightGrams: 125,
    unit: "г",
    price: 830,
    stock: 36, // DEMO
    storage: "Хранить при +2…+8°C",
    shelfLife: "10 суток",
    packageType: "коробка",
    isHalal: true,
    isPopular: true,
    isNew: false,
    image: "assets/products/napoleon.webp",
  },
  {
    id: "medovik",
    slug: "medovik",
    name: "Медовик",
    category: "Десерты",
    subcategory: "Пирожные",
    description: "Тонкие медовые коржи, пропитанные нежным сливочным кремом до мягкости.",
    composition: "Мука пшеничная, масло сливочное, сливки кондитерские, мед натуральный, сахар свекольный, яйцо куриное.",
    compositionKz: "Қамыр, қаймақ (сливки), қант, жұмыртқа, сода",
    weightLabel: "125 грамм",
    weightGrams: 125,
    unit: "г",
    price: 830,
    stock: 29, // DEMO
    storage: "Хранить при +2…+8°C",
    shelfLife: "72 часа",
    packageType: "коробка",
    isHalal: true,
    isPopular: true,
    isNew: false,
    image: "assets/products/medovik.webp",
  },
  {
    id: "molochnaya-devochka",
    slug: "molochnaya-devochka",
    name: "Молочная девочка",
    category: "Десерты",
    subcategory: "Пирожные",
    description: "Нежные коржи на основе сгущенного молока с легким сливочным кремом.",
    composition: "Мука пшеничная, сливки кондитерские, молоко, сахар свекольный, глазурь белая, сыр сливочный, яйцо куриное, сгущенное молоко.",
    compositionKz: "Бисквит, крем, қант, қоюлатылған сүт",
    weightLabel: "125 грамм",
    weightGrams: 125,
    unit: "г",
    price: 820,
    stock: 23, // DEMO
    storage: "Хранить при +2…+8°C",
    shelfLife: "72 часа",
    packageType: "коробка",
    isHalal: true,
    isPopular: true,
    isNew: false,
    image: "assets/products/molochnaya-devochka.webp",
  },
  {
    id: "snikers",
    slug: "snikers",
    name: "Сникерс",
    category: "Десерты",
    subcategory: "Пирожные",
    description: "Шоколадный десерт с арахисом, кремом и насыщенным вкусом в стиле Snickers.",
    composition: "Мука пшеничная, сливочное масло, какао, сливки кондитерские, молоко, арахис, сахар свекольный, шоколад молочный и темный, яйцо куриное.",
    compositionKz: "Бисквит, крем, арахис, қоюлатылған сүт, шоколад, өсімдік майы",
    weightLabel: "160 грамм",
    weightGrams: 160,
    unit: "г",
    price: 1040,
    stock: 29, // DEMO
    storage: "Хранить при +2…+8°C",
    shelfLife: "10 суток",
    packageType: "коробка",
    isHalal: true,
    isPopular: true,
    isNew: false,
    image: "assets/products/snikers.webp",
  },
  {
    id: "ispanskiy-chizkeyk",
    slug: "ispanskiy-chizkeyk",
    name: "Испанский чизкейк",
    category: "Десерты",
    subcategory: "Чизкейки",
    description: "Нежный чизкейк с карамельной корочкой и кремовой текстурой.",
    composition: "Мука пшеничная, сливки кондитерские, сыр сливочный, сахар свекольный, ванильный сахар, яйцо куриное.",
    compositionKz: "Негізі, қаймақ (сливки), қант, ұн, ванильді қант",
    weightLabel: "125 грамм",
    weightGrams: 125,
    unit: "г",
    price: 900,
    stock: 16, // DEMO
    storage: "Хранить при +2…+8°C",
    shelfLife: "72 часа",
    packageType: "коробка",
    isHalal: true,
    isPopular: true,
    isNew: false,
    image: "assets/products/ispanskiy-chizkeyk.webp",
  },
  {
    id: "tary-chizkeyk",
    slug: "tary-chizkeyk",
    name: "Тары чизкейк",
    category: "Десерты",
    subcategory: "Чизкейки",
    description: "Сливочный чизкейк с национальным акцентом тары.",
    composition: "Мука пшеничная, молоко, сливки кондитерские, сыр сливочный, сахар свекольный, ванильный сахар, яйцо куриное, сгущенное молоко, тары (пшено).",
    compositionKz: "Негізі, қаймақ (сливки), тары, сүт, қоюлатылған сүт, қант",
    weightLabel: "125 грамм",
    weightGrams: 125,
    unit: "г",
    price: 890,
    stock: 0, // DEMO
    storage: "Хранить при +2…+8°C",
    shelfLife: "72 часа",
    packageType: "коробка",
    isHalal: true,
    isPopular: false,
    isNew: false,
    image: "assets/products/tary-chizkeyk.webp",
  },
  {
    id: "sinnabon",
    slug: "sinnabon",
    name: "Синнабон",
    category: "Десерты",
    subcategory: "Выпечка",
    description: "Пряная булочка с корицей под сливочной шапкой.",
    composition: "Молоко, яйцо, растительное масло, мука, сливочное масло, тростниковый сахар, сливки, корица.",
    compositionKz: "Қамыр, салма, кілегейлі ірімшік, қаймақ (сливки), қант",
    weightLabel: "150 грамм",
    weightGrams: 150,
    unit: "г",
    price: 600,
    stock: 36, // DEMO
    storage: "Хранить при +2…+8°C",
    shelfLife: "5 суток",
    packageType: "коробка",
    isHalal: true,
    isPopular: true,
    isNew: false,
    image: "assets/products/sinnabon.webp",
  },
  {
    id: "kartoshka",
    slug: "kartoshka",
    name: "Картошка",
    category: "Десерты",
    subcategory: "Пирожные",
    description: "Классический десерт из бисквитной основы с насыщенным шоколадным вкусом.",
    composition: "Яйцо, масло сливочное, мука, какао, сгущенка, шоколад.",
    compositionKz: "Негізі, қоюлатылған сүт, ганаш, ұн, какао",
    weightLabel: "100 грамм",
    weightGrams: 100,
    unit: "г",
    price: 230,
    stock: 4, // DEMO
    storage: "Хранить при +2…+8°C",
    shelfLife: "72 часа",
    packageType: "коробка",
    isHalal: true,
    isPopular: false,
    isNew: false,
    image: "assets/products/kartoshka.webp",
  },
  {
    id: "merengovyy-rulet",
    slug: "merengovyy-rulet",
    name: "Меренговый рулет",
    category: "Десерты",
    subcategory: "Рулеты",
    description: "Воздушная меренга с шелковистым кремом.",
    composition: "Белок, кукурузный крахмал, лимонная кислота, миндальная стружка, сливки, творожный сыр.",
    compositionKz: "Меренга, крем, мармелад, крахмал",
    weightLabel: "130 грамм",
    weightGrams: 130,
    unit: "г",
    price: 890,
    stock: 32, // DEMO
    storage: "Хранить при +2…+8°C",
    shelfLife: "72 часа",
    packageType: "коробка",
    isHalal: true,
    isPopular: false,
    isNew: false,
    image: "assets/products/merengovyy-rulet.webp",
  },
  {
    id: "fistashkovyy-rulet",
    slug: "fistashkovyy-rulet",
    name: "Фисташковый рулет",
    category: "Десерты",
    subcategory: "Рулеты",
    description: "Фисташковый рулет с мягким кремом и ярким вкусом.",
    composition: "Яйца, мука, подсолнечное масло, фисташковая мука, краситель зеленый, сливки, творожный сыр.",
    compositionKz: "Дакуаз, крем, таңқурай конфитюрі, қаймақ (сливки)",
    weightLabel: "134 грамм",
    weightGrams: 134,
    unit: "г",
    price: 990,
    stock: 16, // DEMO
    storage: "Хранить при +2…+8°C",
    shelfLife: "72 часа",
    packageType: "коробка",
    isHalal: true,
    isPopular: true,
    isNew: false,
    image: "assets/products/fistashkovyy-rulet.webp",
  },
  {
    id: "tartaletka-tvorozhnaya",
    slug: "tartaletka-tvorozhnaya",
    name: "Тарталетка творожная",
    category: "Десерты",
    subcategory: "Тарталетки",
    description: "Тарталетка с нежной творожной начинкой и сливочным кремом.",
    composition: "Сливочное масло, яйцо, мука, творог, сметана, ванильный сахар, сливки, творожный сыр.",
    compositionKz: "",
    weightLabel: "165 грамм",
    weightGrams: 165,
    unit: "г",
    price: 750,
    stock: 14, // DEMO
    storage: "Хранить при +2…+8°C",
    shelfLife: "Уточнить",
    packageType: "коробка",
    isHalal: true,
    isPopular: false,
    isNew: false,
    image: null,
  },
  {
    id: "tartaletka-bannofi-pay",
    slug: "tartaletka-bannofi-pay",
    name: "Тарталетка Баннофи Пай",
    category: "Десерты",
    subcategory: "Тарталетки",
    description: "Тарталетка с бананом, варёной сгущёнкой и творожным кремом.",
    composition: "Сливочное масло, яйцо, мука, варёная сгущёнка, банан, творожный сыр, сливки.",
    compositionKz: "",
    weightLabel: "150 грамм",
    weightGrams: 150,
    unit: "г",
    price: 750,
    stock: 14, // DEMO
    storage: "Хранить при +2…+8°C",
    shelfLife: "Уточнить",
    packageType: "коробка",
    isHalal: true,
    isPopular: false,
    isNew: false,
    image: "assets/products/tartaletka-bannofi-pay.webp",
  },
  {
    id: "kukis",
    slug: "kukis",
    name: "Кукис",
    category: "Десерты",
    subcategory: "Пирожные",
    description: "Мягкое печенье с шоколадными каплями и ванильным ароматом.",
    composition: "Сливочное масло, коричневый сахар, яйца, ванильный сахар, мука пшеничная, крахмал кукурузный, шоколадные капли.",
    compositionKz: "Қамыр, қант, жұмыртқа, шоколад тамшылары, крахмал",
    weightLabel: "50–60 грамм",
    weightGrams: 55,
    unit: "г",
    price: 260,
    stock: 15, // DEMO
    storage: "Хранить при +2…+8°C",
    shelfLife: "72 часа",
    packageType: "коробка",
    isHalal: true,
    isPopular: false,
    isNew: true,
    image: "assets/products/kukis.webp",
  },
  {
    id: "maffin-shokoladnyy",
    slug: "maffin-shokoladnyy",
    name: "Маффин шоколадный",
    category: "Десерты",
    subcategory: "Выпечка",
    description: "Влажный шоколадный маффин с насыщенным вкусом какао.",
    composition: "Мука, какао-порошок, яйца, молоко, растительное масло, ванильный сахар, шоколад.",
    compositionKz: "Бисквит, шоколад тамшылары, сүт, өсімдік майы, қант",
    weightLabel: "50–55 грамм",
    weightGrams: 53,
    unit: "г",
    price: 290,
    stock: 16, // DEMO
    storage: "Хранить при +2…+8°C",
    shelfLife: "72 часа",
    packageType: "коробка",
    isHalal: true,
    isPopular: false,
    isNew: false,
    image: "assets/products/maffin-shokoladnyy.webp",
  },
  {
    id: "tort-medovik",
    slug: "tort-medovik",
    name: "Торт Медовик",
    category: "Десерты",
    subcategory: "Торты",
    description: "Цельный медовый торт с мягкими коржами и сливочным кремом.",
    composition: "Мука пшеничная, масло сливочное, сливки кондитерские, мед натуральный, сахар свекольный, яйцо куриное.",
    compositionKz: "Қамыр, қаймақ (сливки), қант, жұмыртқа, сода",
    weightLabel: "1 кг",
    weightGrams: 1000,
    unit: "г",
    price: 6640,
    stock: 34, // DEMO
    storage: "Хранить при +2…+8°C",
    shelfLife: "Уточнить",
    packageType: "коробка",
    isHalal: true,
    isPopular: false,
    isNew: false,
    image: "assets/products/tort-medovik.webp",
  },
  {
    id: "tort-napoleon",
    slug: "tort-napoleon",
    name: "Торт Наполеон",
    category: "Десерты",
    subcategory: "Торты",
    description: "Цельный торт Наполеон с тонкими слоями теста и нежным кремом.",
    composition: "Мука пшеничная, масло сливочное, молоко, яйцо куриное, уксусная эссенция, сливки кондитерские, сахар свекольный, ванильный сахар.",
    compositionKz: "Қамыр, крем, қаймақ (сливки), крахмал, сірке суы",
    weightLabel: "1 кг",
    weightGrams: 1000,
    unit: "г",
    price: 6640,
    stock: 3, // DEMO
    storage: "Хранить при +2…+8°C",
    shelfLife: "Уточнить",
    packageType: "коробка",
    isHalal: true,
    isPopular: false,
    isNew: false,
    image: "assets/products/tort-napoleon.webp",
  },
  {
    id: "tort-molochnaya-devochka",
    slug: "tort-molochnaya-devochka",
    name: "Торт Молочная девочка",
    category: "Десерты",
    subcategory: "Торты",
    description: "Цельный торт Молочная девочка с нежными коржами на сгущенном молоке.",
    composition: "Мука пшеничная, сливки кондитерские, молоко, сахар свекольный, глазурь белая, сыр сливочный, яйцо куриное, сгущенное молоко.",
    compositionKz: "Бисквит, крем, қант, қоюлатылған сүт",
    weightLabel: "1 кг",
    weightGrams: 1000,
    unit: "г",
    price: 6500,
    stock: 0, // DEMO
    storage: "Хранить при +2…+8°C",
    shelfLife: "Уточнить",
    packageType: "коробка",
    isHalal: true,
    isPopular: false,
    isNew: false,
    image: "assets/products/tort-molochnaya-devochka.webp",
  },
  {
    id: "tort-snikers",
    slug: "tort-snikers",
    name: "Торт Сникерс",
    category: "Десерты",
    subcategory: "Торты",
    description: "Цельный шоколадно-арахисовый торт в стиле Сникерс.",
    composition: "Мука пшеничная, сливочное масло, какао, сливки кондитерские, молоко, арахис, сахар свекольный, шоколад молочный и темный, яйцо куриное.",
    compositionKz: "Бисквит, крем, арахис, қоюлатылған сүт, шоколад, өсімдік майы",
    weightLabel: "1,3 кг",
    weightGrams: 1300,
    unit: "г",
    price: 8280,
    stock: 34, // DEMO
    storage: "Хранить при +2…+8°C",
    shelfLife: "Уточнить",
    packageType: "коробка",
    isHalal: true,
    isPopular: true,
    isNew: false,
    image: "assets/products/tort-snikers.webp",
  },
  {
    id: "fistashkovyy-rulet-tselnyy",
    slug: "fistashkovyy-rulet-tselnyy",
    name: "Фисташковый рулет цельный",
    category: "Десерты",
    subcategory: "Рулеты",
    description: "Цельный фисташковый рулет со сливочным кремом.",
    composition: "Яйца, мука, подсолнечное масло, фисташковая мука, краситель зеленый, сливки, творожный сыр.",
    compositionKz: "Дакуаз, крем, таңқурай конфитюрі, қаймақ (сливки)",
    weightLabel: "510 грамм",
    weightGrams: 510,
    unit: "г",
    price: 4990,
    stock: 12, // DEMO
    storage: "Хранить при +2…+8°C",
    shelfLife: "Уточнить",
    packageType: "коробка",
    isHalal: true,
    isPopular: false,
    isNew: false,
    image: "assets/products/fistashkovyy-rulet-tselnyy.webp",
  },
  {
    id: "merengovyy-rulet-tselnyy",
    slug: "merengovyy-rulet-tselnyy",
    name: "Меренговый рулет цельный",
    category: "Десерты",
    subcategory: "Рулеты",
    description: "Цельный меренговый рулет с нежным кремом.",
    composition: "Белок, кукурузный крахмал, лимонная кислота, миндальная стружка, сливки, творожный сыр.",
    compositionKz: "Меренга, крем, мармелад, крахмал",
    weightLabel: "510–550 грамм",
    weightGrams: 530,
    unit: "г",
    price: 3990,
    stock: 28, // DEMO
    storage: "Хранить при +2…+8°C",
    shelfLife: "Уточнить",
    packageType: "коробка",
    isHalal: true,
    isPopular: false,
    isNew: false,
    image: "assets/products/merengovyy-rulet-tselnyy.webp",
  },
  {
    id: "banka-keyk-fistashkovyy",
    slug: "banka-keyk-fistashkovyy",
    name: "Банка-кейк Фисташковый",
    category: "Десерты",
    subcategory: "Банкейки",
    description: "Банка-кейк с фисташковым кремом и насыщенным ореховым вкусом.",
    composition: "Мука фисташковая, мука в/с, масло сливочное, крем фисташковый, арахис, крем для взбивания.",
    compositionKz: "Крамбл, өсімдік кілегейі, пісте пастасы, қант",
    weightLabel: "180 грамм",
    weightGrams: 180,
    unit: "г",
    price: 1100,
    stock: 21, // DEMO
    storage: "Хранить при +2…+4°C",
    shelfLife: "10 суток",
    packageType: "банка",
    isHalal: true,
    isPopular: false,
    isNew: false,
    image: "assets/products/banka-keyk-fistashkovyy.webp",
  },
  {
    id: "banka-keyk-krasnyy-barhat",
    slug: "banka-keyk-krasnyy-barhat",
    name: "Банка-кейк Красный бархат",
    category: "Десерты",
    subcategory: "Банкейки",
    description: "Порционный банка-кейк Красный бархат.",
    composition: "Мука в/с, сливки кондитерские, молоко, масло сливочное, яйцо куриное.",
    compositionKz: "",
    weightLabel: "130 грамм",
    weightGrams: 130,
    unit: "г",
    price: 900,
    stock: 35, // DEMO
    storage: "Хранить при +2…+4°C",
    shelfLife: "10 суток",
    packageType: "банка",
    isHalal: true,
    isPopular: false,
    isNew: false,
    image: null,
  },
  {
    id: "banka-keyk-tiramisu",
    slug: "banka-keyk-tiramisu",
    name: "Банка-кейк Тирамису",
    category: "Десерты",
    subcategory: "Банкейки",
    description: "Кофейный банка-кейк с нежным кремом в стиле тирамису.",
    composition: "Мука в/с, сыр сливочный, желатин, яйцо куриное, кофе, крем для взбивания.",
    compositionKz: "Бисквит, кілегейлі ірімшік, өсімдік кілегейі, желатин, какао, кофе",
    weightLabel: "150 грамм",
    weightGrams: 150,
    unit: "г",
    price: 1000,
    stock: 23, // DEMO
    storage: "Хранить при +2…+4°C",
    shelfLife: "10 суток",
    packageType: "банка",
    isHalal: true,
    isPopular: false,
    isNew: false,
    image: "assets/products/banka-keyk-tiramisu.webp",
  },
  {
    id: "banka-keyk-oreo",
    slug: "banka-keyk-oreo",
    name: "Банка-кейк Орео",
    category: "Десерты",
    subcategory: "Банкейки",
    description: "Шоколадный банка-кейк с кремом и печеньем Орео.",
    composition: "Мука в/с, сливки кондитерские, масло сливочное, яйцо куриное, какао.",
    compositionKz: "Прага бисквиті, 33% қаймақ (сливки), кілегейлі ірімшік, Орео печеньесі",
    weightLabel: "170 грамм",
    weightGrams: 170,
    unit: "г",
    price: 1000,
    stock: 1, // DEMO
    storage: "Хранить при +2…+4°C",
    shelfLife: "10 суток",
    packageType: "банка",
    isHalal: true,
    isPopular: true,
    isNew: false,
    image: "assets/products/banka-keyk-oreo.webp",
  },
  {
    id: "shu-yagodnyy",
    slug: "shu-yagodnyy",
    name: "Шу с малиной",
    category: "Десерты",
    subcategory: "Шу",
    description: "Шу с малиновой начинкой и нежным кремом.",
    composition: "Сливочное масло, соль, сахар, пшеничная мука, яйца, сливки, пюре малины, желатин, малиновый мармелад, белый шоколад, малина.",
    compositionKz: "",
    weightLabel: "170 грамм",
    weightGrams: 170,
    unit: "г",
    price: 700,
    stock: 34, // DEMO
    storage: "Хранить при +2…+4°C",
    shelfLife: "10 суток",
    packageType: "коробка",
    isHalal: true,
    isPopular: false,
    isNew: false,
    image: "assets/products/shu-yagodnyy.webp",
  },
  {
    id: "shu-abrikosovyy",
    slug: "shu-abrikosovyy",
    name: "Шу с абрикосом",
    category: "Десерты",
    subcategory: "Шу",
    description: "Шу с абрикосовой начинкой и нежным кремом.",
    composition: "Сливочное масло, соль, сахар, пшеничная мука, яйца, сливки, пюре абрикоса, желатин, абрикосовый мармелад, мак, белый шоколад.",
    compositionKz: "",
    weightLabel: "170 грамм",
    weightGrams: 170,
    unit: "г",
    price: 700,
    stock: 2, // DEMO
    storage: "Хранить при +2…+4°C",
    shelfLife: "10 суток",
    packageType: "коробка",
    isHalal: true,
    isPopular: false,
    isNew: false,
    image: "assets/products/shu-abrikosovyy.webp",
  },
  {
    id: "denish-s-klubnikoy",
    slug: "denish-s-klubnikoy",
    name: "Дениш с клубникой",
    category: "Десерты",
    subcategory: "Дениши",
    description: "Дениш с клубничной начинкой.",
    composition: "Пшеничная мука, вода, соль, сахар, дрожжи, сливочное масло, молоко, яйца, ваниль, крахмал, клубника.",
    compositionKz: "",
    weightLabel: "170 грамм",
    weightGrams: 170,
    unit: "г",
    price: 600,
    stock: 16, // DEMO
    storage: "Хранить при +2…+4°C",
    shelfLife: "10 суток",
    packageType: "коробка",
    isHalal: true,
    isPopular: false,
    isNew: false,
    image: "assets/products/denish-s-klubnikoy.webp",
  },
  {
    id: "denish-s-persikom",
    slug: "denish-s-persikom",
    name: "Дениш с персиком",
    category: "Десерты",
    subcategory: "Дениши",
    description: "Дениш с персиковой начинкой.",
    composition: "Пшеничная мука, вода, соль, сахар, дрожжи, сливочное масло, молоко, яйца, ваниль, крахмал, персик.",
    compositionKz: "",
    weightLabel: "170 грамм",
    weightGrams: 170,
    unit: "г",
    price: 600,
    stock: 39, // DEMO
    storage: "Хранить при +2…+4°C",
    shelfLife: "10 суток",
    packageType: "коробка",
    isHalal: true,
    isPopular: false,
    isNew: false,
    image: "assets/products/denish-s-persikom.webp",
  },
  {
    id: "molochnaya-devochka-banketnaya",
    slug: "molochnaya-devochka-banketnaya",
    name: "Молочная девочка банкетная",
    category: "Банкетные десерты",
    subcategory: "Банкетный ассортимент",
    description: "Банкетный формат десерта Молочная девочка, цена указана за 1 шт.",
    composition: "Мука пшеничная, сливки кондитерские, молоко, сахар свекольный, глазурь белая, сыр сливочный, яйцо куриное, сгущенное молоко.",
    compositionKz: "Бисквит, крем, қант, қоюлатылған сүт",
    weightLabel: "750 грамм / 12 шт / 65 грамм 1 шт",
    weightGrams: 750,
    unit: "г",
    price: 450,
    stock: 10, // DEMO
    storage: "Хранить при +2…+8°C",
    shelfLife: "Уточнить",
    packageType: "коробка",
    isHalal: true,
    isPopular: false,
    isNew: false,
    image: "assets/products/molochnaya-devochka-banketnaya.webp",
  },
  {
    id: "tort-vuppi-banketnyy",
    slug: "tort-vuppi-banketnyy",
    name: "Торт Вуппи банкетный",
    category: "Банкетные десерты",
    subcategory: "Банкетный ассортимент",
    description: "Банкетный формат торта Вуппи, цена указана за 1 шт.",
    composition: "Яйцо, мука, какао, масло сливочное, сливки, шоколад сикао, фисташковая мука.",
    compositionKz: "",
    weightLabel: "750 грамм / 12 шт / 65 грамм 1 шт",
    weightGrams: 750,
    unit: "г",
    price: 450,
    stock: 30, // DEMO
    storage: "Хранить при +2…+8°C",
    shelfLife: "Уточнить",
    packageType: "коробка",
    isHalal: true,
    isPopular: false,
    isNew: false,
    image: "assets/products/tort-vuppi-banketnyy.webp",
  },
  {
    id: "desert-vupi-pay",
    slug: "desert-vupi-pay",
    name: "Десерт вупи-пай",
    category: "Десерты",
    subcategory: "Пирожные",
    description: "Шоколадные коржи с кремом из сливочного сыра и шоколадным ганашем.",
    composition: "Шоколад, яйцо куриное, сахар, масло сливочное, мука пшеничная, какао, разрыхлитель, сыр сливочный, сливки 33%, ганаш шоколадный.",
    compositionKz: "",
    weightLabel: "125 грамм",
    weightGrams: 125,
    unit: "г",
    price: 950,
    stock: 25, // DEMO
    storage: "Хранить при +2…+4°C",
    shelfLife: "3 суток",
    packageType: "коробка",
    isHalal: true,
    isPopular: false,
    isNew: true,
    image: "assets/products/desert-vupi-pay.webp",
  },
  {
    id: "tort-vupi-pay",
    slug: "tort-vupi-pay",
    name: "Торт вупи-пай",
    category: "Десерты",
    subcategory: "Торты",
    description: "Цельный шоколадный торт вупи-пай с кремом из сливочного сыра и ганашем.",
    composition: "Шоколад, яйцо куриное, сахар, масло сливочное, мука пшеничная, какао, разрыхлитель, сыр сливочный, сливки 33%, ганаш шоколадный.",
    compositionKz: "",
    weightLabel: "1 кг",
    weightGrams: 1000,
    unit: "г",
    price: 7580,
    stock: 11, // DEMO
    storage: "Хранить при +2…+4°C",
    shelfLife: "10 суток",
    packageType: "коробка",
    isHalal: true,
    isPopular: false,
    isNew: true,
    image: "assets/products/tort-vupi-pay.webp",
  },
  {
    id: "desert-dubayskiy",
    slug: "desert-dubayskiy",
    name: "Десерт дубайский",
    category: "Десерты",
    subcategory: "Пирожные",
    description: "Десерт с фисташковой пастой и хрустящим тестом катаифи в дубайском стиле.",
    composition: "Яйцо куриное, сахар, мука пшеничная, какао, разрыхлитель, масло растительное, сливки 33%, сыр сливочный, паста фисташковая, масло сливочное, шоколад, краситель пищевой, тесто катаифи, ганаш шоколадный.",
    compositionKz: "",
    weightLabel: "125 грамм",
    weightGrams: 125,
    unit: "г",
    price: 1450,
    stock: 32, // DEMO
    storage: "Хранить при +2…+4°C",
    shelfLife: "3 суток",
    packageType: "коробка",
    isHalal: true,
    isPopular: false,
    isNew: true,
    image: "assets/products/desert-dubayskiy.webp",
  },
  {
    id: "tort-dubayskiy",
    slug: "tort-dubayskiy",
    name: "Торт дубайский",
    category: "Десерты",
    subcategory: "Торты",
    description: "Цельный торт с фисташковой пастой и хрустящим тестом катаифи в дубайском стиле.",
    composition: "Яйцо куриное, сахар, мука пшеничная, какао, разрыхлитель, масло растительное, сливки 33%, сыр сливочный, паста фисташковая, масло сливочное, шоколад, краситель пищевой, тесто катаифи, ганаш шоколадный.",
    compositionKz: "",
    weightLabel: "1 кг",
    weightGrams: 1000,
    unit: "г",
    price: 11550,
    stock: 18, // DEMO
    storage: "Хранить при +2…+4°C",
    shelfLife: "3 суток",
    packageType: "коробка",
    isHalal: true,
    isPopular: false,
    isNew: true,
    image: "assets/products/tort-dubayskiy.webp",
  },
  {
    id: "desert-fistashka-malina",
    slug: "desert-fistashka-malina",
    name: "Десерт фисташка-малина",
    category: "Десерты",
    subcategory: "Пирожные",
    description: "Фисташковый десерт с сублимированной малиной и сливочным кремом.",
    composition: "Яйцо куриное, сахар, мука пшеничная, паста фисташковая, разрыхлитель, масло растительное, сливки 33%, сыр сливочный, сублимированная малина/ягода, орех фисташки.",
    compositionKz: "",
    weightLabel: "125 грамм",
    weightGrams: 125,
    unit: "г",
    price: 910,
    stock: 21, // DEMO
    storage: "Хранить при +2…+4°C",
    shelfLife: "3 суток",
    packageType: "коробка",
    isHalal: true,
    isPopular: false,
    isNew: true,
    image: "assets/products/desert-fistashka-malina.webp",
  },
  {
    id: "tort-fistashka-malina",
    slug: "tort-fistashka-malina",
    name: "Торт фисташка-малина",
    category: "Десерты",
    subcategory: "Торты",
    description: "Цельный фисташковый торт с сублимированной малиной и сливочным кремом.",
    composition: "Яйцо куриное, сахар, мука пшеничная, паста фисташковая, разрыхлитель, масло растительное, сливки 33%, сыр сливочный, сублимированная малина/ягода, орех фисташки.",
    compositionKz: "",
    weightLabel: "1 кг",
    weightGrams: 1000,
    unit: "г",
    price: 7230,
    stock: 37, // DEMO
    storage: "Хранить при +2…+4°C",
    shelfLife: "10 суток",
    packageType: "коробка",
    isHalal: true,
    isPopular: false,
    isNew: true,
    image: "assets/products/tort-fistashka-malina.webp",
  },
  {
    id: "tort-medovik-banketnyy",
    slug: "tort-medovik-banketnyy",
    name: "Торт Медовик банкетный",
    category: "Банкетные десерты",
    subcategory: "Банкетный ассортимент",
    description: "Банкетный формат торта Медовик, цена указана за 1 шт.",
    composition: "Мука пшеничная, масло сливочное, сливки кондитерские, мед натуральный, сахар свекольный, яйцо куриное.",
    compositionKz: "Қамыр, қаймақ (сливки), қант, жұмыртқа, сода",
    weightLabel: "720 грамм / 12 шт / 65 грамм 1 шт",
    weightGrams: 720,
    unit: "г",
    price: 450,
    stock: 14, // DEMO
    storage: "Хранить при +2…+8°C",
    shelfLife: "Уточнить",
    packageType: "коробка",
    isHalal: true,
    isPopular: false,
    isNew: false,
    image: "assets/products/tort-medovik-banketnyy.webp",
  },
  {
    id: "tort-napoleon-banketnyy",
    slug: "tort-napoleon-banketnyy",
    name: "Торт Наполеон банкетный",
    category: "Банкетные десерты",
    subcategory: "Банкетный ассортимент",
    description: "Банкетный формат торта Наполеон, цена указана за 1 шт.",
    composition: "Мука пшеничная, масло сливочное, молоко, яйцо куриное, уксусная эссенция, сливки кондитерские, сахар свекольный, ванильный сахар.",
    compositionKz: "Қамыр, крем, қаймақ (сливки), крахмал, сірке суы",
    weightLabel: "780 грамм / 12 шт / 65 грамм 1 шт",
    weightGrams: 780,
    unit: "г",
    price: 450,
    stock: 21, // DEMO
    storage: "Хранить при +2…+8°C",
    shelfLife: "Уточнить",
    packageType: "коробка",
    isHalal: true,
    isPopular: false,
    isNew: false,
    image: "assets/products/tort-napoleon-banketnyy.webp",
  },
];

/* --------------------------------------------------------------------------
   5. АКЦИЯ «5 ДЕСЕРТОВ» — реальные условия действующей бонусной программы
   -------------------------------------------------------------------------- */

const PROMO = {
  id: "bonus-100k-week",
  badge: "Бонусная программа",
  title: "5 десертов в подарок за заказы недели",
  summary:
    "Оформляйте заказы на общую сумму от 100 000 ₸ за календарную неделю — и получайте комплимент: пять десертов на выбор вместе со следующим заказом.",
  highlight: { condition: "от 100 000 ₸ в неделю", reward: "5 десертов в подарок" },
  threshold: 100000,
  periodLabel: "с 1 августа по 30 ноября 2026",
  details: [
    "Учитываются подтверждённые, полностью оплаченные и переданные заказы одного участника (один БИН/ИИН) за неделю с понедельника по воскресенье по времени Алматы.",
    "Право на подарок возникает один раз за неделю независимо от суммы превышения.",
    "Подарок передаётся вместе со следующим подтверждённым заказом на следующей календарной неделе, отдельная доставка не производится.",
    "Акционная продукция не обменивается на деньги и не засчитывается как скидка.",
  ],
  tooltip:
    "Сумма считается по подтверждённым и оплаченным заказам одного БИН/ИИН с понедельника по воскресенье.",
  /* Этапы шкалы — визуальный прогресс в стиле программы лояльности. */
  milestones: [
    { value: 35000,  label: "35 000 ₸",  caption: "старт недели" },
    { value: 70000,  label: "70 000 ₸",  caption: "почти у цели" },
    { value: 100000, label: "100 000 ₸", caption: "5 десертов" },
  ],
  /* Три демонстрационных состояния шкалы. */
  states: {
    empty:    { current: 0,      label: "Прогресс 0%" },
    progress: { current: 65000,  label: "Прогресс 65%" },
    reward:   { current: 118400, label: "Награда получена" },
  },
  giftOptions: [
    "Кукис",
    "Маффин шоколадный",
    "Синнабон",
    "Дениш с клубникой",
    "Тарталетка «Баннофи Пай»",
  ],
  giftSlugs: ["kukis", "maffin-shokoladnyy", "sinnabon", "denish-s-klubnikoy", "tartaletka-bannofi-pay"],
};

/* --------------------------------------------------------------------------
   6. СТАТУСЫ ЗАКАЗОВ И ОПЛАТЫ (реальные подписи из проекта)
   -------------------------------------------------------------------------- */

const ORDER_STATUSES = {
  pending_manager_confirmation: { label: "В производстве",        tone: "warning" },
  change_proposed:              { label: "Предложены изменения",  tone: "warning" },
  confirmed_waiting_payment:    { label: "Ожидает оплаты",        tone: "warning" },
  overdue:                      { label: "Просрочен",             tone: "danger"  },
  paid:                         { label: "Оплачен",               tone: "success" },
  delivering:                   { label: "Отгружен",              tone: "info"    },
  completed:                    { label: "Завершён",              tone: "success" },
  canceled:                     { label: "Отменён",               tone: "danger"  },
};

const PAYMENT_STATUSES = {
  unpaid:              { label: "Не оплачен",        tone: "neutral" },
  payment_link_created:{ label: "Счет готов",        tone: "info"    },
  payment_link_sent:   { label: "Счет отправлен",    tone: "info"    },
  partial:             { label: "Частично оплачен",  tone: "warning" },
  paid:                { label: "Оплачен",           tone: "success" },
  failed:              { label: "Ошибка оплаты",     tone: "danger"  },
  expired:             { label: "Ссылка истекла",    tone: "danger"  },
  refunded:            { label: "Возврат",           tone: "neutral" },
};

/* --------------------------------------------------------------------------
   7. ДЕМО-КАБИНЕТ: клиент, адреса, история заказов
   Все значения вымышленные — показывают дизайн, а не реальных клиентов.
   -------------------------------------------------------------------------- */

const PROFILE = {
  company: "Coffee Point",
  contactName: "Айгерим Сатпаева",
  phone: "+7 705 123 45 67",
  email: "accounting@coffeepoint.kz",
  bin: "123456789012",
  clientSince: "апрель 2026",
  tier: "Постоянный партнёр",
  credit: { limit: 400000, used: 118400, available: 281600, nextPaymentDate: "14 августа", nextPaymentSum: 118400, status: "active", statusLabel: "Кредит активен" },
  weekTotal: 65000,
  addresses: [
    { id: "a1", title: "Основная точка", value: "г. Алматы, пр. Достык 132, кофейня", isDefault: true },
    { id: "a2", title: "Вторая точка",   value: "г. Алматы, ул. Байтурсынова 22, корнер", isDefault: false },
  ],
};

const ORDERS = [
  {
    number: "DC-2607-0148",
    date: "24 июля 2026",
    dateShort: "24.07.2026",
    status: "pending_manager_confirmation",
    payment: "unpaid",
    total: 67960,
    positions: 4,
    units: 88,
    deliveryDate: "24 июля 2026",
    deliveryAddress: "г. Алматы, пр. Достык 132, кофейня",
    deliveryTime: "Утро 8-12",
    items: [
      { slug: "tort-medovik", name: "Торт Медовик", qty: 4, price: 6640, sum: 26560, image: "assets/products/tort-medovik.webp" },
      { slug: "medovik", name: "Медовик", qty: 20, price: 830, sum: 16600, image: "assets/products/medovik.webp" },
      { slug: "kukis", name: "Кукис", qty: 40, price: 260, sum: 10400, image: "assets/products/kukis.webp" },
      { slug: "sinnabon", name: "Синнабон", qty: 24, price: 600, sum: 14400, image: "assets/products/sinnabon.webp" },
    ],
  },
  {
    number: "DC-2607-0139",
    date: "18 июля 2026",
    dateShort: "18.07.2026",
    status: "confirmed_waiting_payment",
    payment: "payment_link_sent",
    total: 65408,
    positions: 3,
    units: 32,
    deliveryDate: "18 июля 2026",
    deliveryAddress: "г. Алматы, пр. Достык 132, кофейня",
    deliveryTime: "Утро 8-12",
    items: [
      { slug: "pelmeni-s-govyadinoy", name: "Пельмени с говядиной", qty: 12, price: 2124, sum: 25488, image: "assets/products/pelmeni-s-govyadinoy.webp" },
      { slug: "manty-s-govyadinoy-i-tykvoy", name: "Манты с говядиной и тыквой", qty: 10, price: 2060, sum: 20600, image: "assets/products/manty-s-govyadinoy-i-tykvoy.webp" },
      { slug: "samsa-s-govyadinoy-i-tykvoy", name: "Самса с говядиной и тыквой", qty: 10, price: 1932, sum: 19320, image: "assets/products/samsa-s-govyadinoy-i-tykvoy.webp" },
    ],
  },
  {
    number: "DC-2607-0121",
    date: "11 июля 2026",
    dateShort: "11.07.2026",
    status: "delivering",
    payment: "paid",
    total: 57280,
    positions: 4,
    units: 62,
    deliveryDate: "11 июля 2026",
    deliveryAddress: "г. Алматы, пр. Достык 132, кофейня",
    deliveryTime: "Утро 8-12",
    items: [
      { slug: "ispanskiy-chizkeyk", name: "Испанский чизкейк", qty: 18, price: 900, sum: 16200, image: "assets/products/ispanskiy-chizkeyk.webp" },
      { slug: "napoleon", name: "Наполеон", qty: 20, price: 830, sum: 16600, image: "assets/products/napoleon.webp" },
      { slug: "snikers", name: "Сникерс", qty: 12, price: 1040, sum: 12480, image: "assets/products/snikers.webp" },
      { slug: "banka-keyk-tiramisu", name: "Банка-кейк Тирамису", qty: 12, price: 1000, sum: 12000, image: "assets/products/banka-keyk-tiramisu.webp" },
    ],
  },
  {
    number: "DC-2606-0104",
    date: "4 июля 2026",
    dateShort: "04.07.2026",
    status: "completed",
    payment: "paid",
    total: 55980,
    positions: 4,
    units: 53,
    deliveryDate: "4 июля 2026",
    deliveryAddress: "г. Алматы, пр. Достык 132, кофейня",
    deliveryTime: "Утро 8-12",
    items: [
      { slug: "tort-napoleon", name: "Торт Наполеон", qty: 3, price: 6640, sum: 19920, image: "assets/products/tort-napoleon.webp" },
      { slug: "tort-snikers", name: "Торт Сникерс", qty: 2, price: 8280, sum: 16560, image: "assets/products/tort-snikers.webp" },
      { slug: "maffin-shokoladnyy", name: "Маффин шоколадный", qty: 30, price: 290, sum: 8700, image: "assets/products/maffin-shokoladnyy.webp" },
      { slug: "denish-s-klubnikoy", name: "Дениш с клубникой", qty: 18, price: 600, sum: 10800, image: "assets/products/denish-s-klubnikoy.webp" },
    ],
  },
  {
    number: "DC-2606-0092",
    date: "27 июня 2026",
    dateShort: "27.06.2026",
    status: "canceled",
    payment: "refunded",
    total: 28784,
    positions: 2,
    units: 14,
    deliveryDate: "27 июня 2026",
    deliveryAddress: "г. Алматы, пр. Достык 132, кофейня",
    deliveryTime: "Утро 8-12",
    items: [
      { slug: "syrniki-klassicheskie", name: "Сырники классические", qty: 8, price: 1228, sum: 9824, image: "assets/products/syrniki-klassicheskie.webp" },
      { slug: "kotlety-govyazhi", name: "Котлеты говяжьи", qty: 6, price: 3160, sum: 18960, image: "assets/products/kotlety-govyazhi.webp" },
    ],
  },
];

/* --------------------------------------------------------------------------
   8. ТЕКСТЫ СТРАНИЦ (реальные формулировки сайта)
   -------------------------------------------------------------------------- */

const CONTENT = {
  hero: {
    eyebrow: "B2B-поставки · Алматы",
    title: "Надёжные поставки\nдля вашего бизнеса",
    subtitle:
      "Десерты, полуфабрикаты и мясо для кофеен, ресторанов, отелей и магазинов. Оптовые цены, живые остатки, история заказов — всё в одном кабинете.",
    stats: [
      { value: "50+",   caption: "партнёров по Казахстану" },
      { value: "98%",   caption: "заказов без замечаний" },
      { value: "Халал", caption: "вся мясная линейка" },
      { value: "100%",  caption: "собственное производство" },
    ],
  },
  about: {
    title: "DC Bakery — B2B поставщик еды в Казахстане",
    text:
      "Мы специализируемся на поставках продуктов питания для B2B-сегмента: кофеен, ресторанов, гостиниц и магазинов. Работаем с 50+ партнёрами по всему Казахстану.",
    footerText:
      "B2B-каталог десертов, полуфабрикатов и мясных позиций для кофеен, ресторанов, магазинов и отелей.",
  },
  advantages: [
    { title: "Открытые B2B-цены",        text: "Прайс виден сразу, без запроса и торгового представителя." },
    { title: "Минимальный заказ 15 000 ₸", text: "От минимума доставка бесплатная по Алматы." },
    { title: "Живые остатки",            text: "Каталог показывает, чего мало, а чего нет — до оформления." },
    { title: "Повтор заказа за 2 минуты", text: "История заявок в кабинете, повтор в один тап." },
    { title: "Документы под 1С",         text: "Счёт, накладная и АВР — в кабинете и на почте." },
    { title: "Собственное производство", text: "Пекарня и цех полуфабрикатов, вся мясная линейка — халал." },
  ],
  orderSteps: [
    { n: "01", title: "Заказ",        text: "Соберите корзину в каталоге — минимум 15 000 ₸." },
    { n: "02", title: "Подтверждение",text: "Менеджер проверит остатки и слот доставки." },
    { n: "03", title: "Счёт",         text: "Счёт с реквизитами приходит в WhatsApp и на почту." },
    { n: "04", title: "Доставка",     text: "Вт · чт · сб. Приём заявок до 18:00 накануне." },
  ],
  delivery: {
    title: "Доставка под ваш график поставок",
    text: "Способ (доставка или самовывоз) и точные сроки согласуются при подтверждении заказа менеджером.",
    cards: [
      { value: "15 000 ₸",      caption: "Минимальный заказ" },
      { value: "0 ₸",           caption: "Доставка от минимума" },
      { value: "1 500–3 000 ₸", caption: "Доставка ниже минимума" },
    ],
    notes: [
      "При заказе от 15 000 тенге доставка бесплатная.",
      "При меньшей сумме возможна доплата за доставку 1 500–3 000 тенге по усмотрению Поставщика.",
      "Способ (доставка или самовывоз) и точные сроки согласуются при подтверждении заказа менеджером.",
    ],
  },
  payment: [
    {
      title: "Банковской картой онлайн",
      text: "Visa / Mastercard через защищённую платёжную страницу банка-эквайера. Данные карты вводятся на стороне банка и на сайте не хранятся. Средства списываются в момент оформления заказа.",
    },
    {
      title: "По счёту (безналичный расчёт)",
      text: "Для одобренных B2B-клиентов — на условиях консигнации 3–4 дня. Оплата согласно выставленному счёту на банковский счёт Поставщика.",
    },
  ],
  refund: [
    "Продукция скоропортящаяся. Товар надлежащего качества возврату не подлежит.",
    "Претензии по количеству и качеству принимаются только в момент приёмки и фиксируются актом. После подписания накладной претензии не рассматриваются.",
    "При выявлении производственного брака Поставщик производит замену, допоставку или возврат стоимости.",
    "Возврат средств по оплате картой — на ту же карту в срок до 10 рабочих дней с момента согласования возврата.",
  ],
};

/* --------------------------------------------------------------------------
   9. ЭКСПОРТ В ГЛОБАЛЬНУЮ ОБЛАСТЬ (прототип без сборки — обычные скрипты)
   -------------------------------------------------------------------------- */

window.DC = {
  CONFIG,
  CONTACTS,
  REQUISITES,
  CATEGORIES,
  COLLECTIONS,
  COLLECTION_ITEMS,
  PRODUCTS,
  PROMO,
  ORDER_STATUSES,
  PAYMENT_STATUSES,
  PROFILE,
  ORDERS,
  CONTENT,
};
