"use client";

import { useState, type SyntheticEvent } from "react";
import Image, { type ImageProps } from "next/image";
import { getCategoryIcon, isAutoGeneratedPlaceholder } from "@/src/lib/categoryIcon";

type FallbackImageProps = Omit<ImageProps, "src"> & {
  categoryId?: string;
  categorySlug?: string;
  src?: ImageProps["src"];
};

function CategoryIconPlaceholder({ icon }: { icon: string }) {
  return (
    <div className="absolute inset-0 flex items-center justify-center bg-coral-light/60">
      <div className="flex h-[60%] w-[60%] items-center justify-center rounded-full bg-coral-light">
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img src={icon} alt="" aria-hidden className="h-[70%] w-[70%] object-contain" />
      </div>
    </div>
  );
}

function GenericPlaceholder() {
  return (
    <div className="absolute inset-0 flex flex-col items-center justify-center bg-gradient-to-br from-coral-light to-cream">
      <svg
        width="44"
        height="44"
        viewBox="0 0 48 48"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        className="text-gray-300"
      >
        <path d="M8 28 C8 12 40 12 40 28" stroke="currentColor" strokeWidth="2" strokeLinecap="round" />
        <rect x="21" y="8" width="6" height="5" rx="3" fill="currentColor" />
        <line x1="4" y1="32" x2="44" y2="32" stroke="currentColor" strokeWidth="2" strokeLinecap="round" />
        <path d="M10 32 Q24 40 38 32" stroke="currentColor" strokeWidth="2" strokeLinecap="round" />
      </svg>
      <span className="mt-1.5 text-xs font-medium tracking-widest text-gray-300">DC</span>
    </div>
  );
}

export function FallbackImage({
  alt,
  categoryId,
  categorySlug,
  onError,
  src,
  ...props
}: FallbackImageProps) {
  const [failed, setFailed] = useState(false);

  const srcString = typeof src === "string" ? src : undefined;
  const showFallback = !src || failed || isAutoGeneratedPlaceholder(srcString);

  if (showFallback) {
    const icon = getCategoryIcon(categoryId) ?? getCategoryIcon(categorySlug);
    if (icon) return <CategoryIconPlaceholder icon={icon} />;
    return <GenericPlaceholder />;
  }

  function handleError(event: SyntheticEvent<HTMLImageElement, Event>) {
    setFailed(true);
    onError?.(event);
  }

  return <Image {...props} alt={alt} src={src} onError={handleError} />;
}
